// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClaimsSupportFilterSearchController from "./claims_support_filter_search_controller"
application.register("claims-support-filter-search", ClaimsSupportFilterSearchController )

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import SelectAutocompleteController from "./select_autocomplete_controller"
application.register("select-autocomplete", SelectAutocompleteController)
