---
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
    better_html_config: .better-html.yml
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/ArgumentAlignment:
        Enabled: false
      Layout/CommentIndentation:
        Enabled: false
      Layout/FirstArgumentIndentation:
        Enabled: false
      Layout/FirstArrayElementIndentation:
        Enabled: false
      Layout/FirstHashElementIndentation:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Style/StringLiterals:
        Enabled: true
        EnforcedStyle: double_quotes
