inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/AccessModifierIndentation:
  EnforcedStyle: indent
