inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/AccessModifierIndentation:
  EnforcedStyle: indent

RSpec/Capybara/FeatureMethods:
  EnabledMethods:
    - scenario

# Switch off deprecated cop
RSpec/FilePath:
  Enabled: false

# And replace with the preferred cops
RSpec/SpecFilePathFormat:
  Enabled: true
  CustomTransform:
    DfESignInUser: dfe_sign_in_user
    DfESignIn: dfe_sign_in

RSpec/SpecFilePathSuffix:
  Enabled: true
