require:
  - rubocop-rspec

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml
  pundit:
    - config/rubocop-rspec.yml

inherit_mode:
  merge:
    - Exclude

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Layout/AccessModifierIndentation:
  EnforcedStyle: indent

Lint/MissingSuper:
  AllowedParentClasses:
    - ApplicationService

RSpec/Dialect:
  Enabled: true
  Exclude:
    - spec/support/shared_examples/system/**/*.rb
  PreferredMethods:
    background: :before
    given: :let
    given!: :let!
    feature: :describe

RSpec/IndexedLet:
  Enabled: false

# Switch off deprecated cop
Rails/FilePath:
  Enabled: false

# And replace with the preferred cops
RSpec/SpecFilePathFormat:
  Enabled: true
  CustomTransform:
    DfESignInUser: dfe_sign_in_user
    DfESignIn: dfe_sign_in

RSpec/SpecFilePathSuffix:
  Enabled: true

RSpec/VerifiedDoubleReference:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/placements/application_controller.rb

RSpec/NoExpectationExample:
  Exclude:
    - spec/support/shared_examples/system/**/*.rb
    - spec/smoke_tests/**/*.rb
