name: Deploy environment
description: Deploys an application environment

inputs:
  environment:
    description: The name of the environment
    required: true
  docker-image:
    description: The Docker image to deploy
    required: true
  azure-credentials:
    description: JSON object containing a service principal that can read from Azure Key Vault
    required: true
  pull-request-number:
    description: The pull request number which triggered this deploy.
    required: false

runs:
  using: composite

  steps:
          - uses: hashicorp/setup-terraform@v3
            with:
              terraform_version: 1.6.4
              terraform_wrapper: false

          - uses: DFE-Digital/github-actions/set-kubelogin-environment@master
            with:
              azure-credentials: ${{ inputs.azure-credentials }}

          - name: Terraform Apply
            shell: bash
            run: |
              make ci ${{ inputs.environment }} terraform-apply
            env:
              DOCKER_IMAGE_TAG: ${{ inputs.docker-image }}
              PR_NUMBER: ${{ inputs.pull-request-number }}

          - name: Extract Terraform outputs
            shell: bash
            id: set_outputs
            run: |
              output=$(terraform -chdir=terraform/application output -json hostname)
              echo "HOSTNAMES=$output" >> $GITHUB_ENV

          - name: Set up Ruby 3.3.0
            uses: ruby/setup-ruby@v1
            with:
              ruby-version: 3.3.0
              bundler-cache: true

          - name: Run RSpec tests
            shell: bash
            run: |
             CLAIMS_EXTERNAL_HOST=$(echo $HOSTNAMES | jq -r '.[0]')
             PLACEMENTS_EXTERNAL_HOST=$(echo $HOSTNAMES | jq -r '.[1]')

             export CLAIMS_EXTERNAL_HOST=$CLAIMS_EXTERNAL_HOST
             export PLACEMENTS_EXTERNAL_HOST=$PLACEMENTS_EXTERNAL_HOST

             bin/bundle exec rspec --tag smoke_test -b
            env:
                SMOKE_TEST: "true"
                HOSTNAMES: ${{ env.HOSTNAMES }}
