CONFIG=dv_review
CONFIG_SHORT=rv
AZURE_SUBSCRIPTION=s189-teacher-services-cloud-development
AZURE_RESOURCE_PREFIX=s189d01
KV_PURGE_PROTECTION=false
TERRAFORM_MODULES_TAG=2615-spike-nginx-ingress-controller-replacement-istio
