apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: track-and-pay-temp.pr-1797.test.teacherservices.cloud
spec:
  ingressClassName: nginx
  rules:
  - host: track-and-pay-temp.pr-1797.test.teacherservices.cloud
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: itt-mentor-services-pr-1797
            port:
              number: 80
