---
shared:
  :partnerships:
    - id
    - school_id
    - provider_id
    - created_at
    - updated_at
  :mentor_trainings:
    - id
    - training_type
    - hours_completed
    - date_completed
    - claim_id
    - mentor_id
    - provider_id
    - created_at
    - updated_at
    - rejected
    - reason_rejected
    - not_assured
    - reason_not_assured
    - reason_clawed_back
    - hours_clawed_back
  :user_memberships:
    - id
    - user_id
    - organisation_type
    - organisation_id
    - created_at
    - updated_at
  :users:
    - first_name
    - last_name
    - created_at
    - updated_at
    - id
    - type
    - dfe_sign_in_uid
    - last_signed_in_at
    - discarded_at
  :trusts:
    - id
    - uid
    - name
    - created_at
    - updated_at
  :subjects:
    - id
    - subject_area
    - name
    - code
    - parent_subject_id
    - created_at
    - updated_at
  :regions:
    - id
    - name
    - claims_funding_available_per_hour_pence
    - claims_funding_available_per_hour_currency
    - created_at
    - updated_at
  :placement_mentor_joins:
    - id
    - mentor_id
    - placement_id
    - created_at
    - updated_at
  :mentors:
    - first_name
    - last_name
    - trn
    - id
    - created_at
    - updated_at
  :mentor_memberships:
    - id
    - type
    - mentor_id
    - school_id
    - created_at
    - updated_at
  :claims:
    - id
    - school_id
    - created_at
    - updated_at
    - provider_id
    - reference
    - submitted_at
    - created_by_type
    - created_by_id
    - status
    - submitted_by_type
    - submitted_by_id
    - reviewed
    - claim_window_id
    - sampling_reason
    - payment_in_progress_at
    - unpaid_reason
  :samplings:
    - id
    - created_at
    - updated_at
  :provider_samplings:
    - id
    - sampling_id
    - provider_id
    - created_at
    - updated_at
    - downloaded_at
  :provider_sampling_claims:
    - id
    - claim_id
    - provider_sampling_id
    - created_at
    - updated_at
  :clawbacks:
    - id
    - created_at
    - updated_at
    - downloaded_at
  :clawback_claims:
    - id
    - claim_id
    - clawback_id
    - created_at
    - updated_at
  :schools:
    - id
    - urn
    - placements_service
    - claims_service
    - created_at
    - updated_at
    - name
    - postcode
    - town
    - ukprn
    - telephone
    - website
    - address1
    - address2
    - address3
    - group
    - type_of_establishment
    - phase
    - gender
    - minimum_age
    - maximum_age
    - religious_character
    - admissions_policy
    - urban_or_rural
    - school_capacity
    - total_pupils
    - total_girls
    - total_boys
    - percentage_free_school_meals
    - special_classes
    - send_provision
    - rating
    - last_inspection_date
    - email_address
    - district_admin_name
    - district_admin_code
    - region_id
    - trust_id
    - longitude
    - latitude
    - local_authority_name
    - local_authority_code
    - claims_grant_conditions_accepted_at
    - claims_grant_conditions_accepted_by_id
    - expression_of_interest_completed
    - vendor_number
  :providers:
    - id
    - code
    - created_at
    - updated_at
    - placements_service
    - provider_type
    - name
    - ukprn
    - urn
    - website
    - address1
    - address2
    - address3
    - town
    - city
    - county
    - postcode
    - accredited
  :placements:
    - id
    - school_id
    - subject_id
    - created_at
    - updated_at
    - provider_id
    - year_group
    - academic_year_id
  :school_contacts:
    - id
    - school_id
    - created_at
    - updated_at
  :placement_additional_subjects:
    - id
    - subject_id
    - placement_id
    - created_at
    - updated_at
  :academic_years:
    - id
    - name
    - starts_on
    - ends_on
    - created_at
    - updated_at
  :claim_windows:
    - id
    - academic_year_id
    - starts_on
    - ends_on
    - created_at
    - updated_at
    - discarded_at
  :terms:
    - id
    - name
    - created_at
    - updated_at
  :placement_windows:
    - id
    - placement_id
    - term_id
    - created_at
    - updated_at
  :payments:
    - id
    - sent_by_id
    - created_at
    - updated_at
    - downloaded_at
  :payment_claims:
    - id
    - payment_id
    - claim_id
    - created_at
    - updated_at
  :payment_responses:
    - id
    - user_id
    - processed
    - created_at
    - updated_at
    - downloaded_at
  :claim_activities:
    - id
    - action
    - user_id
    - record_type
    - record_id
    - created_at
    - updated_at
