default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: itt_mentor_services_development

test:
  <<: *default
  database: itt_mentor_services_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: itt_mentor_services_production
