# Define scheduled jobs (cron jobs) in this file.
#
# EXAMPLE CONFIG
#
# name-of-job:
#   cron: "* * * * * *" # also accepts natural language, e.g. "every second"
#   class: NameOfAJob
#   description: Description is shown in the GoodJob dashboard.
publish_provider_sync:
  cron: "15 0 * * *"
  class: "PublishTeacherTraining::Provider::SyncAllJob"
  description: "Sync all providers with data imported from Publish Teacher Training"

gias_school_sync:
  cron: "30 23 * * *"
  class: "Gias::SyncAllSchoolsJob"
  description: "Import/Update Schools using GIAS data"

teaching_record_mentor_sync:
  cron: "5 0 * * *"
  class: "TeachingRecord::SyncAllMentorsJob"
  description: "Sync all mentor first and last name attributes"

publish_subject_sync:
  cron: "0 0 * * *"
  class: "PublishTeacherTraining::Subject::SyncAllJob"
  description: "Sync all subjects with data imported from Publish Teacher Training"

remove_internal_draft_claims:
  cron: "10 0 * * *"
  class: "Claims::RemoveInternalDraftClaimsJob"
  description: "Remove all internal_draft claims"

remove_unprocessed_claims_payment_responses:
  cron: "20 0 * * *" # Every day at 00:20.
  class: "Claims::RemoveUnprocessedPaymentResponsesJob"
  description: "Remove unprocessed claims payment responses"

send_entity_table_checks_to_bigquery:
  cron: "30 0 * * *" # Every day at 00:30.
  class: "DfE::Analytics::EntityTableCheckJob"
  queue: dfe_analytics
  description: "Syncs the entity table in BigQuery with the database"

trim_expired_sessions:
  cron: "15 * * * *" # Every hour at quarter past
  class: "TrimExpiredSessionsJob"
  description: "Trim old sessions from the database"

send_claims_slack_daily_roundup:
  cron: "0 16 * * *" # Every day at 16:00
  class: "Claims::Slack::DailyRoundupJob"
  description: "Sends a daily roundup Slack message"

notify_claims_users_they_have_invalid_provider_claims:
  cron: "0 9 * * MON" # Every monday at 9:00
  class: "Claims::User::NotifyUsersOfInvalidProviderClaimsJob"
  description: "Reminds users to address claims with invalid providers"

remind_providers_to_respond_to_sampling:
    cron: "0 9 * * MON" # Every monday at 10:00
    class: "Claims::Sampling::RemindProvidersToRespondJob"
    description: "Reminds providers to respond to audit requests"

remind_schools_to_respond_to_sampling:
    cron: "0 9 * * TUE" # Every monday at 10:00
    class: "Claims::Sampling::RemindSchoolsToRespondJob"
    description: "Reminds schools to respond to audit requests"
