# Define scheduled jobs (cron jobs) in this file.
#
# EXAMPLE CONFIG
#
# name-of-job:
#   cron: "* * * * * *" # also accepts natural language, e.g. "every second"
#   class: NameOfAJob
#   description: Description is shown in the GoodJob dashboard.
publish_provider_sync:
  cron: "15 0 * * *"
  class: "PublishTeacherTraining::Provider::SyncAllJob"
  description: "Sync all providers with data imported from Publish Teacher Training"

gias_school_sync:
  cron: "30 23 * * *"
  class: "Gias::SyncAllSchoolsJob"
  description: "Import/Update Schools using GIAS data"

teaching_record_mentor_sync:
  cron: "5 0 * * *"
  class: "TeachingRecord::SyncAllMentorsJob"
  description: "Sync all mentor first and last name attributes"

publish_subject_sync:
  cron: "0 0 * * *"
  class: "PublishTeacherTraining::Subject::SyncAllJob"
  description: "Sync all subjects with data imported from Publish Teacher Training"
