# Define scheduled jobs (cron jobs) in this file.
#
# EXAMPLE CONFIG
#
# name-of-job:
#   cron: "* * * * * *" # also accepts natural language, e.g. "every second"
#   class: NameOfAJob
#   description: Description is shown in the GoodJob dashboard.
publish_provider_sync:
  cron: "15 0 * * *"
  class: "PublishTeacherTraining::Provider::SyncAllJob"
  description: "Sync all providers with data imported from Publish Teacher Training"

gias_school_sync:
  cron: "30 23 * * *"
  class: "Gias::SyncAllSchoolsJob"
  description: "Import/Update Schools using GIAS data"

teaching_record_mentor_sync:
  cron: "5 0 * * *"
  class: "TeachingRecord::SyncAllMentorsJob"
  description: "Sync all mentor first and last name attributes"

publish_subject_sync:
  cron: "0 0 * * *"
  class: "PublishTeacherTraining::Subject::SyncAllJob"
  description: "Sync all subjects with data imported from Publish Teacher Training"

remove_internal_draft_claims:
  cron: "10 0 * * *"
  class: "Claims::RemoveInternalDraftClaimsJob"
  description: "Remove all internal_draft claims"

send_entity_table_checks_to_bigquery:
  cron: "30 0 * * *"  # Every day at 00:30.
  class: "DfE::Analytics::EntityTableCheckJob"
  queue: dfe_analytics
  description: "Syncs the entity table in BigQuery with the database"
