---
HOSTING_ENV: review
SKYLIGHT_ENV: review

# API integrations
GIAS_CSV_BASE_URL: https://ea-edubase-api-prod.azurewebsites.net/edubase/downloads/public
PUBLISH_BASE_URL: https://qa.api.publish-teacher-training-courses.service.gov.uk
TEACHING_RECORD_BASE_URL: https://preprod.teacher-qualifications-api.education.gov.uk
TEACHING_RECORD_API_MINOR_VERSION: 20240416

# User authentication
SIGN_IN_METHOD: persona

# DfE Analytics gem
BIGQUERY_TABLE_NAME: events
BIGQUERY_PROJECT_ID: rugged-abacus-218110
BIGQUERY_DATASET: itt_mentor_events_qa
