name: Delete review app on AKS

on:
  pull_request:
    branches:
    - main
    types:
    - closed

concurrency: deploy-${{ github.event.number }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'deploy') }}
    environment: review

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.4
        terraform_wrapper: false

    - uses: DFE-Digital/github-actions/set-kubelogin-environment@master
      with:
        azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Destroy
      run: |
        make ci review terraform-destroy
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}

    - name: Post Pull Request Comment
      if: ${{ github.event_name == 'pull_request' }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: aks
        message: |
                Review app  track and pay deployed to <https://track-and-pay-${{ github.event.number }}.test.teacherservices.cloud> was deleted
                Review app  school placements deployed to <https://manage-school-placements-${{ github.event.number }}.test.teacherservices.cloud> was deleted
