name: Deploy Domains Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
        - qa
        - staging
        - sandbox
        - production

jobs:
  deploy_domains_env:
    name: Deploy Environment Domains
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Fetch secrets from key vault
        uses: azure/CLI@v2
        id: keyvault-yaml-secret
        with:
          inlineScript: |
            SLACK_WEBHOOK=$(az keyvault secret show --name "SLACK-WEBHOOK" --vault-name "${{ secrets.INF_KEY_VAULT }}" --query "value" -o tsv)
            echo "::add-mask::$SLACK_WEBHOOK"
            echo "SLACK_WEBHOOK=$SLACK_WEBHOOK" >> $GITHUB_OUTPUT

      - name: Deploy Domains Environment
        id: deploy_domains_env
        uses: DFE-Digital/github-actions/deploy-domains-env@ci-cd-domains
        with:
          azure-credentials:  ${{ secrets.AZURE_CREDENTIALS }}
          environment: ${{ inputs.environment }}
          healthcheck: healthcheck/all
          slack-webhook: ${{ steps.keyvault-yaml-secret.outputs.SLACK_WEBHOOK }}
